<?php
/**
 * Kpspace_News extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Kpspace
 * @package        Kpspace_News
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * NewsItem link widget template
 *
 * @category    Kpspace
 * @package     Kpspace_News
 * @author      Ultimate Module Creator
 */
?>
<?php $_newstbl = $this->getCurrentNewstbl();?>
<?php if ($_newstbl) :?>
    <div class="newstbl-widget-link">
        <a href="<?php echo $_newstbl->getNewstblUrl()?>"><?php echo $_newstbl->getHeading()?></a>
    </div>
<?php endif;?>
