<?php
/**
 * Kpspace_News extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Kpspace
 * @package        Kpspace_News
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * NewsItem view template
 *
 * @category    Kpspace
 * @package     Kpspace_News
 * @author      Ultimate Module Creator
 */
?>
<?php $_newstbl = $this->getCurrentNewstbl();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title newstbl-title">
    <h1><?php echo $_newstbl->getHeading(); ?></h1>
</div>
<div class="newstbl-view">
    <div class="newstbl-heading">
        <?php echo Mage::helper('kpspace_news')->__('Heading');?>:<?php echo $_newstbl->getHeading();?>

    </div>

</div>
