<form action="<?php echo Mage::getUrl('test/index/save') ?>" method="post">
    <fieldset>
        <ul>
            <li>
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom"/>
            </li>
            <li>
                <label for="prenom">PreNom</label>
                <input type="text" id="prenom" name="prenom"/>
            </li>
            <li>
                <label for="telephone">Telephone</label>
                <input type="text" id="telephone" name="telephone"/>
            </li>
            <li>
                <input type='submit' value='save'/>
            </li>
        </ul>
    </fieldset>
</form>
<?php
echo $this->methodblock();

?>